
import { Dimensions, StyleSheet } from 'react-native';
import { colors } from '@/constants/theme';
import { radius } from '@/theme/radius';
import { spacing } from '@/theme/spacing';
import { fontSizes, fonts } from '@/theme/typography';

const { width: W } = Dimensions.get('window');
const HORIZONTAL = 20;
const ACTION_WIDTH = (W - HORIZONTAL * 2 - 28) / 4;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: { paddingBottom: spacing['8'] },

  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: HORIZONTAL,
    paddingTop: spacing['2.5'],
    paddingBottom: spacing['3.5'],
    gap: spacing['3'],
  },
  profileHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['3'],
  },
  profileAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.surface,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileAvatarText: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.primary,
  },
  profileMeta: {
    flex: 1,
    minWidth: 0,
  },
  profileName: {
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 23,
    color: colors.text,
  },
  profileRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['2'],
    marginTop: 5,
  },
  profileRoleBadge: {
    paddingHorizontal: 9,
    paddingVertical: spacing['1'],
    borderRadius: radius['pill'],
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
  },
  profileRoleText: {
    fontFamily: fonts.semibold,
    fontSize: 11,
    lineHeight: 14,
    color: colors.primary,
  },
  profileArea: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 16,
    color: colors.muted,
  },
  profileAreaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 5,
  },
  headerNotificationButton: {
    width: 44,
    height: 44,
    borderRadius: radius['cardLarge'],
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  locationGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['2.5'],
  },
  locationIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['1'],
  },
  locationTitle: {
    maxWidth: 168,
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 24,
    color: colors.text,
  },
  locationSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 17,
    color: colors.muted,
    marginTop: 1,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['2.5'],
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: radius['cardLarge'],
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  bellBadge: {
    position: 'absolute',
    top: 5,
    right: 5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.surface,
  },
  bellBadgeText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes['2xs'],
    color: colors.surface,
  },
  weatherCard: {
    minWidth: 96,
    height: 48,
    borderRadius: radius['2xl'],
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: spacing['2.5'],
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  weatherIconWrap: {
    width: 28,
    height: 28,
    borderRadius: radius['control'],
    backgroundColor: '#FFFBEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weatherTemp: {
    fontFamily: fonts.bold,
    fontSize: 14,
    lineHeight: 17,
    color: colors.text,
  },
  weatherLabel: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['2xs'],
    lineHeight: 13,
    color: colors.muted,
  },

  heroCard: {
    marginHorizontal: HORIZONTAL,
    minHeight: 210,
    borderRadius: radius['3xl'],
    overflow: 'hidden',
    backgroundColor: '#2563EB',
    padding: spacing['6'],
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.22,
    shadowRadius: 28,
    elevation: 8,
  },
  heroGlowA: {
    position: 'absolute',
    left: -40,
    top: -60,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: 'rgba(147,197,253,0.5)',
  },
  heroGlowB: {
    position: 'absolute',
    right: -56,
    bottom: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(14,165,233,0.36)',
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 162,
  },
  heroCopy: {
    width: '58%',
    justifyContent: 'center',
    zIndex: 2,
  },
  heroLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes['sm'],
    lineHeight: 18,
    color: 'rgba(255,255,255,0.92)',
    marginBottom: spacing['2'],
  },
  heroTitle: {
    fontFamily: fonts.bold,
    fontSize: fontSizes['2xl'],
    lineHeight: 31,
    color: colors.surface,
    marginBottom: spacing['2'],
  },
  heroSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 18,
    color: 'rgba(255,255,255,0.86)',
    marginBottom: 18,
  },
  heroPrimaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing['3'],
    backgroundColor: colors.surface,
    paddingLeft: 18,
    paddingRight: spacing['2'],
    height: 50,
    borderRadius: 25,
    alignSelf: 'flex-start',
    minWidth: 162,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  heroPrimaryText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['base'],
    color: colors.primary,
  },
  heroButtonIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroIllustration: {
    flex: 1,
    minHeight: 160,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  heroCityImage: {
    position: 'absolute',
    right: -26,
    bottom: -8,
    width: 190,
    height: 148,
    borderTopLeftRadius: 58,
    opacity: 0.58,
  },
  heroCloud: {
    position: 'absolute',
    top: 22,
    right: 36,
    width: 58,
    height: 22,
    borderRadius: radius['control'],
    backgroundColor: 'rgba(255,255,255,0.78)',
  },
  heroPhoneCard: {
    position: 'absolute',
    right: 64,
    bottom: 76,
    width: 34,
    height: 44,
    borderRadius: radius['md'],
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
  },
  heroCitizen: {
    position: 'absolute',
    right: 52,
    bottom: 18,
    alignItems: 'center',
  },
  heroCitizenHead: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FACC15',
    borderWidth: 3,
    borderColor: '#1D4ED8',
  },
  heroCitizenBody: {
    width: 58,
    height: 70,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: '#1E40AF',
    marginTop: -2,
  },
  heroTreeA: {
    position: 'absolute',
    right: -2,
    bottom: 10,
    width: 42,
    height: 58,
    borderRadius: radius['2xl'],
    backgroundColor: '#22C55E',
  },
  heroTreeB: {
    position: 'absolute',
    right: 22,
    bottom: 0,
    width: 30,
    height: 40,
    borderRadius: radius['card'],
    backgroundColor: '#16A34A',
  },

  section: { paddingHorizontal: HORIZONTAL, marginTop: 26 },
  sectionTight: { paddingHorizontal: HORIZONTAL, marginTop: 18 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing['3.5'],
    gap: spacing['3'],
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 19,
    lineHeight: 25,
    color: colors.text,
  },
  sectionSub: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 17,
    color: colors.muted,
    marginTop: spacing['0.5'],
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['0.5'],
    paddingVertical: spacing['2'],
  },
  sectionActionText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['sm'],
    color: colors.primary,
  },

  quickActionsPanel: {
    minHeight: 132,
    borderRadius: radius['3xl'],
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    paddingHorizontal: spacing['3.5'],
    paddingVertical: spacing['4'],
    borderWidth: 1,
    borderColor: '#EEF2F7',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 22,
    elevation: 4,
  },
  actionItem: {
    width: ACTION_WIDTH,
  },
  actionPressable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 9,
  },
  actionIconWrap: {
    width: 54,
    height: 54,
    borderRadius: radius['card'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['xs'],
    lineHeight: 16,
    color: colors.text,
    textAlign: 'center',
  },

  mapSkeleton: {
    height: 220,
    borderRadius: radius['3xl'],
    overflow: 'hidden',
    backgroundColor: colors.surface,
    padding: spacing['4'],
    borderWidth: 1,
    borderColor: colors.border,
  },
  mapCard: {
    backgroundColor: colors.surface,
    borderRadius: radius['3xl'],
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 26,
    elevation: 7,
  },
  mapHeaderOverlay: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing['3'],
    paddingHorizontal: spacing['4'],
    paddingTop: spacing['3.5'],
    paddingBottom: spacing['3'],
    backgroundColor: colors.surface,
  },
  mapIllustration: {
    height: 182,
    backgroundColor: colors.primarySoft,
  },
  mapTitle: {
    fontFamily: fonts.bold,
    fontSize: 16,
    lineHeight: 21,
    color: colors.text,
  },
  mapCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 3,
  },
  mapCountDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.emerald,
  },
  mapSubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 16,
    color: colors.muted,
  },
  mapLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['0.5'],
    paddingTop: 1,
  },
  mapLinkText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['sm'],
    color: colors.primary,
  },
  mapPinUser: {
    width: 23,
    height: 23,
    borderRadius: radius['md'],
    backgroundColor: colors.primary,
    borderWidth: 4,
    borderColor: colors.surface,
  },
  mapPin: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.emerald,
    borderWidth: 4,
    borderColor: colors.surface,
  },
  mapPinHot: {
    backgroundColor: colors.red,
  },
  mapPinWarn: {
    backgroundColor: colors.amber,
  },
  mapStrongRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['2.5'],
  },
  mapStrongTitle: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    lineHeight: 19,
    color: colors.text,
  },
  mapStrongMeta: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 17,
    color: colors.muted,
    marginTop: spacing['0.5'],
  },
  mapTicketCard: {
    margin: spacing['3'],
    marginTop: -34,
    zIndex: 4,
    backgroundColor: colors.surface,
    borderRadius: radius['card'],
    padding: 13,
    borderWidth: 1,
    borderColor: '#E6EEF8',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },

  featuredRow: {
    gap: spacing['3.5'],
    paddingRight: spacing['2'],
  },
  featuredSkeleton: {
    width: 238,
    height: 206,
    borderRadius: radius['cardLarge'],
    overflow: 'hidden',
  },
  featuredCard: {
    width: 238,
    borderRadius: radius['cardLarge'],
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.09,
    shadowRadius: 18,
    elevation: 4,
  },
  featuredPressable: {
    padding: spacing['2.5'],
  },
  featuredImageWrap: {
    width: '100%',
    height: 108,
    borderRadius: radius['lg'],
    overflow: 'hidden',
    backgroundColor: colors.border,
    marginBottom: 11,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  featuredImageFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.borderLight,
  },
  featuredCollageRow: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    gap: spacing['0.5'],
  },
  featuredCollageHalf: {
    flex: 1,
    height: '100%',
  },
  featuredCollageMain: {
    flex: 1.25,
    height: '100%',
  },
  featuredCollageStack: {
    flex: 0.85,
    height: '100%',
    gap: spacing['0.5'],
  },
  featuredCollageSmall: {
    flex: 1,
    width: '100%',
  },
  featuredCollageSmallWrap: {
    flex: 1,
    overflow: 'hidden',
  },
  featuredMoreOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.46)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  featuredMoreText: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.surface,
  },
  distanceBadge: {
    position: 'absolute',
    left: 9,
    bottom: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radius['pill'],
  },
  distanceText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes['xs'],
    color: colors.surface,
  },
  featuredTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['base'],
    lineHeight: 20,
    color: colors.text,
    minHeight: 40,
  },
  featuredMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 7,
  },
  featuredAddress: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    color: colors.muted,
  },
  featuredStatusRow: {
    marginTop: spacing['2'],
    alignItems: 'flex-start',
  },

  communityBlock: { gap: spacing['3'] },
  communitySkeleton: {
    height: 132,
    borderRadius: radius['cardLarge'],
    overflow: 'hidden',
  },
  communityHeroCard: {
    borderRadius: radius['3xl'],
    backgroundColor: '#F5F3FF',
    overflow: 'hidden',
    padding: spacing['4'],
    borderWidth: 1,
    borderColor: '#EDE9FE',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 5,
  },
  communityGlow: {
    position: 'absolute',
    right: -48,
    bottom: -60,
    width: 172,
    height: 172,
    borderRadius: 86,
    backgroundColor: 'rgba(196,181,253,0.56)',
  },
  communityHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing['3'],
    marginBottom: spacing['3.5'],
  },
  communitySectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 24,
    color: '#6D28D9',
  },
  communitySectionSub: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 17,
    color: '#7C3AED',
    opacity: 0.8,
  },
  communityCta: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing['1'],
  },
  communityCtaText: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['xs'],
    color: '#6D28D9',
  },
  communityBodyRow: {
    flexDirection: 'row',
    gap: spacing['3'],
  },
  communityMiniList: {
    flex: 1,
    gap: spacing['2.5'],
  },
  communityMiniCard: {
    minHeight: 84,
    borderRadius: radius['card'],
    backgroundColor: 'rgba(255,255,255,0.9)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing['2.5'],
    padding: spacing['2.5'],
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  communityMiniImage: {
    width: 68,
    height: 68,
    borderRadius: radius['control'],
    backgroundColor: '#EDE9FE',
  },
  communityNewPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 7,
    paddingVertical: spacing['0.5'],
    borderRadius: radius['pill'],
    backgroundColor: '#8B5CF6',
    marginBottom: 3,
  },
  communityNewText: {
    fontFamily: fonts.bold,
    fontSize: fontSizes['2xs'],
    color: colors.surface,
  },
  communityMiniTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['sm'],
    lineHeight: 18,
    color: colors.text,
  },
  communityMiniAddress: {
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 15,
    color: colors.muted,
    marginTop: 3,
  },
  communityStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: spacing['1.5'],
  },
  communityStatText: {
    fontFamily: fonts.regular,
    fontSize: 11,
    color: '#6B7280',
    marginRight: spacing['1'],
  },
  communityIllustration: {
    width: 96,
    alignSelf: 'stretch',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  communityPersonA: {
    position: 'absolute',
    bottom: 0,
    left: 8,
    width: 44,
    height: 72,
    borderRadius: radius['cardLarge'],
    backgroundColor: '#8B5CF6',
  },
  communityPersonB: {
    position: 'absolute',
    bottom: 0,
    right: 2,
    width: 48,
    height: 82,
    borderRadius: radius['2xl'],
    backgroundColor: '#22C55E',
  },
  communityHeartBubble: {
    position: 'absolute',
    top: 22,
    right: 8,
    width: 34,
    height: 34,
    borderRadius: radius['md'],
    backgroundColor: '#FCE7F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityChatBubble: {
    position: 'absolute',
    top: 48,
    left: 4,
    width: 34,
    height: 34,
    borderRadius: radius['md'],
    backgroundColor: '#EDE9FE',
    alignItems: 'center',
    justifyContent: 'center',
  },

  myReportsGrid: {
    flexDirection: 'row',
    gap: spacing['2.5'],
  },
  myReportSkeleton: {
    flex: 1,
    height: 112,
    borderRadius: radius['xl'],
    overflow: 'hidden',
  },
  myReportCard: {
    flex: 1,
    minHeight: 112,
    borderRadius: radius['cardLarge'],
    borderWidth: 1,
    borderColor: 'rgba(226,232,240,0.85)',
    overflow: 'hidden',
  },
  myReportPressable: {
    flex: 1,
    padding: spacing['3.5'],
    justifyContent: 'space-between',
  },
  myReportCount: {
    fontFamily: fonts.bold,
    fontSize: fontSizes['2xl'],
    lineHeight: 30,
    color: colors.text,
  },
  myReportLabel: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['xs'],
    lineHeight: 16,
  },
  myReportIconWrap: {
    width: 32,
    height: 32,
    borderRadius: radius['md'],
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginTop: spacing['1'],
  },

  emptyStateCard: {
    backgroundColor: colors.surface,
    borderRadius: radius['2xl'],
    padding: spacing['5'],
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    gap: spacing['2.5'],
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  emptyTitle: {
    fontFamily: fonts.semibold,
    fontSize: fontSizes['base'],
    color: colors.text,
  },
  emptySubtitle: {
    fontFamily: fonts.regular,
    fontSize: fontSizes['xs'],
    lineHeight: 18,
    color: colors.muted,
    textAlign: 'center',
    maxWidth: 270,
  },
  chatWrap: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    alignItems: 'flex-end',
  },
});
