/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Brand aligned to web CSS variables
        primary: {
          DEFAULT: '#0B56D9',
          dark: '#0846A8',
          soft: '#EFF6FF',
          muted: '#DBEAFE',
        },
        // Neutrals aligned to web background/surface tokens
        background: '#F8FAFC',
        surface: '#FFFFFF',
        publicSurface: 'rgba(248, 251, 255, 0.97)',
        publicSurfaceSoft: 'rgba(232, 239, 248, 0.95)',
        publicSurfaceStrong: '#F7FAFF',
        text: {
          DEFAULT: '#0F172A',
          secondary: '#334155',
          muted: '#64748B',
          light: '#94A3B8',
          inverse: '#FFFFFF',
        },
        border: {
          DEFAULT: '#E2E8F0',
          light: '#F1F5F9',
          strong: '#CBD5E1',
        },
        // Semantic status colors
        status: {
          pending: { DEFAULT: '#F59E0B', bg: '#FEF3C7', text: '#92400E' },
          processing: { DEFAULT: '#3B82F6', bg: '#EFF6FF', text: '#1D4ED8' },
          waiting: { DEFAULT: '#8B5CF6', bg: '#EDE9FE', text: '#5B21B6' },
          resolved: { DEFAULT: '#10B981', bg: '#D1FAE5', text: '#047857' },
          closed: { DEFAULT: '#64748B', bg: '#F1F5F9', text: '#374151' },
          rejected: { DEFAULT: '#EF4444', bg: '#FEE2E2', text: '#991B1B' },
        },
        // Supporting palette
        emerald: { DEFAULT: '#10B981', light: '#D1FAE5', dark: '#047857' },
        red: { DEFAULT: '#EF4444', light: '#FEE2E2', dark: '#991B1B' },
        amber: { DEFAULT: '#F59E0B', light: '#FEF3C7', dark: '#92400E' },
        purple: { DEFAULT: '#7C3AED', light: '#EDE9FE', dark: '#5B21B6' },
        slate: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
      },
      fontFamily: {
        sans: ['Geist-Regular'],
        'sans-medium': ['Geist-Medium'],
        'sans-semibold': ['Geist-SemiBold'],
        'sans-bold': ['Geist-Bold'],
        'sans-extrabold': ['Geist-ExtraBold'],
        'sans-black': ['Geist-Black'],
        'sans-light': ['Geist-Light'],
        'sans-thin': ['Geist-Thin'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['15px', { lineHeight: '22px' }],
        md: ['15px', { lineHeight: '22px' }],
        lg: ['17px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
        '4xl': ['32px', { lineHeight: '40px' }],
        '5xl': ['36px', { lineHeight: '44px' }],
      },
      borderRadius: {
        sm: '8px',
        DEFAULT: '12px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        full: '9999px',
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '18': '72px',
        '20': '80px',
        '24': '96px',
        'safe-bottom': '34px',
        'tab-bar': '80px',
      },
      letterSpacing: {
        tightest: '-0.05em',
        tighter: '-0.025em',
        tight: '-0.01em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
    },
  },
  plugins: [],
};
