import type { QuickAction } from '../types';

export const QUICK_ACTIONS: QuickAction[] = [
  {
    id: 'create',
    icon: 'edit-3',
    label: 'Phản ánh hiện trường',
    sub: 'Gửi vấn đề mới',
    href: '/(resident)/create-feedback',
    accent: '#0F766E',
    bg: '#F0FDF9',
    iconBg: '#D1FAE5',
    textColor: '#0F172A',
    subColor: '#0F766E',
  },
  {
    id: 'tickets',
    icon: 'search',
    label: 'Theo dõi phản ánh',
    sub: 'Tiến độ xử lý',
    href: '/(resident)/tickets',
    accent: '#2563EB',
    bg: '#EFF6FF',
    iconBg: '#DBEAFE',
    textColor: '#0F172A',
    subColor: '#2563EB',
  },
  {
    id: 'community',
    icon: 'users',
    label: 'Cộng đồng đô thị',
    sub: 'Cùng chung tay',
    href: '/(resident)/community',
    accent: '#F59E0B',
    bg: '#FFFBEB',
    iconBg: '#FEF3C7',
    textColor: '#0F172A',
    subColor: '#B45309',
  },
  {
    id: 'map',
    icon: 'map',
    label: 'Bản đồ đô thị',
    sub: 'Sự cố quanh bạn',
    href: '/(resident)/community/map',
    accent: '#8B5CF6',
    bg: '#F5F3FF',
    iconBg: '#EDE9FE',
    textColor: '#0F172A',
    subColor: '#6D28D9',
  },
];
